person = [{
    "id": 1,
    "first_name": "Lyndy",
    "last_name": "Gatrell",
    "size": "M",
    "gender": "Female",
    "krajina": "BR"
  }, {
    "id": 2,
    "first_name": "Karol",
    "last_name": "Bavester",
    "size": "XL",
    "gender": "Female",
    "krajina": "RU"
  }, {
    "id": 3,
    "first_name": "Joaquin",
    "last_name": "Molineaux",
    "size": "XL",
    "gender": "Male",
    "krajina": "ID"
  }, {
    "id": 4,
    "first_name": "Gianna",
    "last_name": "Gozney",
    "size": "XL",
    "gender": "Female",
    "krajina": "PH"
  }, {
    "id": 5,
    "first_name": "Erina",
    "last_name": "Martinovsky",
    "size": "XS",
    "gender": "Female",
    "krajina": "BR"
  }, {
    "id": 6,
    "first_name": "Ches",
    "last_name": "Merrigan",
    "size": "XS",
    "gender": "Male",
    "krajina": "BR"
  }, {
    "id": 7,
    "first_name": "Isaiah",
    "last_name": "Laphorn",
    "size": "L",
    "gender": "Male",
    "krajina": "US"
  }, {
    "id": 8,
    "first_name": "Sada",
    "last_name": "Berrington",
    "size": "3XL",
    "gender": "Female",
    "krajina": "PT"
  }, {
    "id": 9,
    "first_name": "Ryan",
    "last_name": "Hernik",
    "size": "XS",
    "gender": "Male",
    "krajina": "RU"
  }, {
    "id": 10,
    "first_name": "Ashby",
    "last_name": "Luney",
    "size": "XL",
    "gender": "Male",
    "krajina": "CA"
  }, {
    "id": 11,
    "first_name": "Catlin",
    "last_name": "Raggatt",
    "size": "XS",
    "gender": "Female",
    "krajina": "BR"
  }, {
    "id": 12,
    "first_name": "Ellwood",
    "last_name": "Squier",
    "size": "2XL",
    "gender": "Male",
    "krajina": "ZA"
  }, {
    "id": 13,
    "first_name": "Pip",
    "last_name": "Giacomini",
    "size": "L",
    "gender": "Male",
    "krajina": "CN"
  }, {
    "id": 14,
    "first_name": "Krista",
    "last_name": "Seston",
    "size": "L",
    "gender": "Female",
    "krajina": "BR"
  }, {
    "id": 15,
    "first_name": "Lilian",
    "last_name": "Stilling",
    "size": "S",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 16,
    "first_name": "Curry",
    "last_name": "Skoate",
    "size": "M",
    "gender": "Male",
    "krajina": "MX"
  }, {
    "id": 17,
    "first_name": "Jarrod",
    "last_name": "Petheridge",
    "size": "2XL",
    "gender": "Male",
    "krajina": "IE"
  }, {
    "id": 18,
    "first_name": "Bernadene",
    "last_name": "Coyle",
    "size": "XS",
    "gender": "Female",
    "krajina": "PK"
  }, {
    "id": 19,
    "first_name": "Shayne",
    "last_name": "Acarson",
    "size": "L",
    "gender": "Male",
    "krajina": "BG"
  }, {
    "id": 20,
    "first_name": "Ellen",
    "last_name": "Swinn",
    "size": "L",
    "gender": "Female",
    "krajina": "UA"
  }, {
    "id": 21,
    "first_name": "Angie",
    "last_name": "Horbath",
    "size": "XS",
    "gender": "Male",
    "krajina": "CN"
  }, {
    "id": 22,
    "first_name": "Timmi",
    "last_name": "Charon",
    "size": "XS",
    "gender": "Female",
    "krajina": "US"
  }, {
    "id": 23,
    "first_name": "Maurie",
    "last_name": "Lawrance",
    "size": "L",
    "gender": "Male",
    "krajina": "CV"
  }, {
    "id": 24,
    "first_name": "Lance",
    "last_name": "Flowerden",
    "size": "L",
    "gender": "Male",
    "krajina": "JP"
  }, {
    "id": 25,
    "first_name": "Erwin",
    "last_name": "Willstrop",
    "size": "L",
    "gender": "Male",
    "krajina": "MA"
  }, {
    "id": 26,
    "first_name": "Mattheus",
    "last_name": "Crosbie",
    "size": "XS",
    "gender": "Male",
    "krajina": "CN"
  }, {
    "id": 27,
    "first_name": "Byrann",
    "last_name": "Perren",
    "size": "3XL",
    "gender": "Male",
    "krajina": "PT"
  }, {
    "id": 28,
    "first_name": "Nobe",
    "last_name": "Littrell",
    "size": "XS",
    "gender": "Male",
    "krajina": "BR"
  }, {
    "id": 29,
    "first_name": "Dougie",
    "last_name": "Lanfare",
    "size": "XL",
    "gender": "Male",
    "krajina": "US"
  }, {
    "id": 30,
    "first_name": "Gery",
    "last_name": "Arrington",
    "size": "XS",
    "gender": "Male",
    "krajina": "CZ"
  }, {
    "id": 31,
    "first_name": "Hammad",
    "last_name": "Aggott",
    "size": "XS",
    "gender": "Male",
    "krajina": "PH"
  }, {
    "id": 32,
    "first_name": "Hurlee",
    "last_name": "Panchin",
    "size": "XL",
    "gender": "Male",
    "krajina": "US"
  }, {
    "id": 33,
    "first_name": "Ardra",
    "last_name": "Bullar",
    "size": "2XL",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 34,
    "first_name": "Abey",
    "last_name": "Nealy",
    "size": "2XL",
    "gender": "Male",
    "krajina": "AR"
  }, {
    "id": 35,
    "first_name": "Carroll",
    "last_name": "Coley",
    "size": "L",
    "gender": "Female",
    "krajina": "SA"
  }, {
    "id": 36,
    "first_name": "Dell",
    "last_name": "Graben",
    "size": "M",
    "gender": "Female",
    "krajina": "PK"
  }, {
    "id": 37,
    "first_name": "Laurel",
    "last_name": "Hawsby",
    "size": "2XL",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 38,
    "first_name": "Boothe",
    "last_name": "Skelhorne",
    "size": "3XL",
    "gender": "Male",
    "krajina": "MD"
  }, {
    "id": 39,
    "first_name": "Kellia",
    "last_name": "Manoch",
    "size": "S",
    "gender": "Female",
    "krajina": "JP"
  }, {
    "id": 40,
    "first_name": "Erena",
    "last_name": "Pieroni",
    "size": "S",
    "gender": "Female",
    "krajina": "RU"
  }, {
    "id": 41,
    "first_name": "Lucias",
    "last_name": "Jancey",
    "size": "3XL",
    "gender": "Male",
    "krajina": "CN"
  }, {
    "id": 42,
    "first_name": "Cordula",
    "last_name": "Conkie",
    "size": "XL",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 43,
    "first_name": "Jeanie",
    "last_name": "Witherspoon",
    "size": "2XL",
    "gender": "Female",
    "krajina": "PL"
  }, {
    "id": 44,
    "first_name": "Jobye",
    "last_name": "Boulstridge",
    "size": "XL",
    "gender": "Female",
    "krajina": "PT"
  }, {
    "id": 45,
    "first_name": "Pietro",
    "last_name": "Eads",
    "size": "3XL",
    "gender": "Male",
    "krajina": "HR"
  }, {
    "id": 46,
    "first_name": "Jewelle",
    "last_name": "Dootson",
    "size": "3XL",
    "gender": "Female",
    "krajina": "FR"
  }, {
    "id": 47,
    "first_name": "Missie",
    "last_name": "Mizen",
    "size": "XS",
    "gender": "Female",
    "krajina": "PT"
  }, {
    "id": 48,
    "first_name": "Griffith",
    "last_name": "Sprowles",
    "size": "XS",
    "gender": "Male",
    "krajina": "YE"
  }, {
    "id": 49,
    "first_name": "Lazar",
    "last_name": "Froome",
    "size": "S",
    "gender": "Male",
    "krajina": "CN"
  }, {
    "id": 50,
    "first_name": "Brandise",
    "last_name": "Waber",
    "size": "M",
    "gender": "Female",
    "krajina": "PS"
  }, {
    "id": 51,
    "first_name": "Corty",
    "last_name": "Jeaneau",
    "size": "L",
    "gender": "Male",
    "krajina": "FR"
  }, {
    "id": 52,
    "first_name": "Bobby",
    "last_name": "Tue",
    "size": "M",
    "gender": "Male",
    "krajina": "GR"
  }, {
    "id": 53,
    "first_name": "Kanya",
    "last_name": "Ohanessian",
    "size": "XS",
    "gender": "Female",
    "krajina": "JP"
  }, {
    "id": 54,
    "first_name": "Carl",
    "last_name": "Halegarth",
    "size": "L",
    "gender": "Male",
    "krajina": "NO"
  }, {
    "id": 55,
    "first_name": "Morissa",
    "last_name": "Slesser",
    "size": "XL",
    "gender": "Female",
    "krajina": "GR"
  }, {
    "id": 56,
    "first_name": "Aurelia",
    "last_name": "Portail",
    "size": "XL",
    "gender": "Female",
    "krajina": "SE"
  }, {
    "id": 57,
    "first_name": "Durand",
    "last_name": "Ugolotti",
    "size": "3XL",
    "gender": "Male",
    "krajina": "CN"
  }, {
    "id": 58,
    "first_name": "Isiahi",
    "last_name": "Keyes",
    "size": "S",
    "gender": "Male",
    "krajina": "CF"
  }, {
    "id": 59,
    "first_name": "Valentina",
    "last_name": "Edwards",
    "size": "S",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 60,
    "first_name": "Luis",
    "last_name": "Brizell",
    "size": "XL",
    "gender": "Male",
    "krajina": "GR"
  }, {
    "id": 61,
    "first_name": "Brandon",
    "last_name": "Gilston",
    "size": "3XL",
    "gender": "Male",
    "krajina": "CO"
  }, {
    "id": 62,
    "first_name": "Sullivan",
    "last_name": "Pirelli",
    "size": "XL",
    "gender": "Male",
    "krajina": "PE"
  }, {
    "id": 63,
    "first_name": "Woodie",
    "last_name": "Jimenez",
    "size": "3XL",
    "gender": "Male",
    "krajina": "FR"
  }, {
    "id": 64,
    "first_name": "Noel",
    "last_name": "Ickeringill",
    "size": "M",
    "gender": "Male",
    "krajina": "ID"
  }, {
    "id": 65,
    "first_name": "Giovanni",
    "last_name": "Craney",
    "size": "XL",
    "gender": "Male",
    "krajina": "RU"
  }, {
    "id": 66,
    "first_name": "Calla",
    "last_name": "Wilcock",
    "size": "3XL",
    "gender": "Female",
    "krajina": "JP"
  }, {
    "id": 67,
    "first_name": "Kristoffer",
    "last_name": "Ray",
    "size": "XL",
    "gender": "Male",
    "krajina": "CN"
  }, {
    "id": 68,
    "first_name": "Gonzales",
    "last_name": "Selwyne",
    "size": "3XL",
    "gender": "Male",
    "krajina": "AM"
  }, {
    "id": 69,
    "first_name": "Frankie",
    "last_name": "Biaggioli",
    "size": "L",
    "gender": "Female",
    "krajina": "FR"
  }, {
    "id": 70,
    "first_name": "Dalt",
    "last_name": "Mattusov",
    "size": "2XL",
    "gender": "Male",
    "krajina": "DJ"
  }, {
    "id": 71,
    "first_name": "Corenda",
    "last_name": "Garrand",
    "size": "XL",
    "gender": "Female",
    "krajina": "IS"
  }, {
    "id": 72,
    "first_name": "Erv",
    "last_name": "Coppenhall",
    "size": "3XL",
    "gender": "Male",
    "krajina": "PH"
  }, {
    "id": 73,
    "first_name": "Christen",
    "last_name": "Crass",
    "size": "3XL",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 74,
    "first_name": "Morlee",
    "last_name": "Misken",
    "size": "L",
    "gender": "Male",
    "krajina": "CO"
  }, {
    "id": 75,
    "first_name": "Tracee",
    "last_name": "Succamore",
    "size": "L",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 76,
    "first_name": "Darbie",
    "last_name": "Leakner",
    "size": "S",
    "gender": "Female",
    "krajina": "PT"
  }, {
    "id": 77,
    "first_name": "Florida",
    "last_name": "Swindley",
    "size": "XS",
    "gender": "Female",
    "krajina": "UA"
  }, {
    "id": 78,
    "first_name": "Ferdy",
    "last_name": "Lydiard",
    "size": "XL",
    "gender": "Male",
    "krajina": "RU"
  }, {
    "id": 79,
    "first_name": "Josselyn",
    "last_name": "Burnall",
    "size": "XS",
    "gender": "Female",
    "krajina": "ID"
  }, {
    "id": 80,
    "first_name": "Bidget",
    "last_name": "Imlin",
    "size": "3XL",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 81,
    "first_name": "Stanford",
    "last_name": "Doblin",
    "size": "XL",
    "gender": "Male",
    "krajina": "KZ"
  }, {
    "id": 82,
    "first_name": "Mufinella",
    "last_name": "Thinn",
    "size": "L",
    "gender": "Female",
    "krajina": "TH"
  }, {
    "id": 83,
    "first_name": "Sumner",
    "last_name": "Deighton",
    "size": "L",
    "gender": "Male",
    "krajina": "ID"
  }, {
    "id": 84,
    "first_name": "Marney",
    "last_name": "Roblou",
    "size": "M",
    "gender": "Female",
    "krajina": "RU"
  }, {
    "id": 85,
    "first_name": "Bobbee",
    "last_name": "Stabler",
    "size": "XL",
    "gender": "Female",
    "krajina": "FR"
  }, {
    "id": 86,
    "first_name": "Deerdre",
    "last_name": "Jessup",
    "size": "S",
    "gender": "Female",
    "krajina": "PE"
  }, {
    "id": 87,
    "first_name": "Myra",
    "last_name": "Gynni",
    "size": "XL",
    "gender": "Female",
    "krajina": "AR"
  }, {
    "id": 88,
    "first_name": "Chrissy",
    "last_name": "Warder",
    "size": "XL",
    "gender": "Male",
    "krajina": "CN"
  }, {
    "id": 89,
    "first_name": "Corbin",
    "last_name": "Slany",
    "size": "2XL",
    "gender": "Male",
    "krajina": "PH"
  }, {
    "id": 90,
    "first_name": "Vitia",
    "last_name": "Cortez",
    "size": "3XL",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 91,
    "first_name": "Dru",
    "last_name": "Pinkard",
    "size": "2XL",
    "gender": "Male",
    "krajina": "SE"
  }, {
    "id": 92,
    "first_name": "Tulley",
    "last_name": "Caswell",
    "size": "XL",
    "gender": "Male",
    "krajina": "CZ"
  }, {
    "id": 93,
    "first_name": "Ashleigh",
    "last_name": "Widocks",
    "size": "L",
    "gender": "Female",
    "krajina": "BR"
  }, {
    "id": 94,
    "first_name": "Hildagard",
    "last_name": "Du Pre",
    "size": "S",
    "gender": "Female",
    "krajina": "UA"
  }, {
    "id": 95,
    "first_name": "Rosalia",
    "last_name": "Dare",
    "size": "L",
    "gender": "Female",
    "krajina": "FR"
  }, {
    "id": 96,
    "first_name": "Amil",
    "last_name": "Lomen",
    "size": "2XL",
    "gender": "Female",
    "krajina": "PK"
  }, {
    "id": 97,
    "first_name": "Sybille",
    "last_name": "Cisco",
    "size": "L",
    "gender": "Female",
    "krajina": "CN"
  }, {
    "id": 98,
    "first_name": "Pierrette",
    "last_name": "Labadini",
    "size": "XS",
    "gender": "Female",
    "krajina": "ID"
  }, {
    "id": 99,
    "first_name": "Ashla",
    "last_name": "Brafield",
    "size": "S",
    "gender": "Female",
    "krajina": "EG"
  }, {
    "id": 100,
    "first_name": "Duff",
    "last_name": "Raspin",
    "size": "M",
    "gender": "Male",
    "krajina": "MW"
  }]

  const baseURL = 'https://eshop.sk/:';

  function getURL() {

    person.forEach(val => {
        console.log(baseURL+val.id+'/detail');
    })

  }
  
  const GENDER = {
      'Male' : 0,
      'Female': 0
  }

  function HowMany() {
    const x = 100;
    person.forEach(val => {
        GENDER[val.gender]++;
    });
    console.log(GENDER);
    console.log((GENDER.Male/person.length)*x +'%');
    console.log((GENDER.Female/person.length)*x+'%');
   }


const countryCode = {};

function findCountry() { 

    person.forEach(val => {
        if(countryCode[val.krajina] === undefined) {
            countryCode[val.krajina] = 1;
        } else {
            countryCode[val.krajina]++;
        }
    })
    console.log(countryCode);
}

console.log(findCountry());


